#!/bin/bash -f
#set dst = (-50 -100 -150 -200)
ut=(0 3 6 9 12 15 18 21)
TU=(00 03 06 09 12 15 18 21)

for year in 2025 2020 2015 2010 2005 2000 1995 1990 1985 1980 1975 1970 1965 1960 1955
#mkdir $year
cd $year
echo $year
i=9

while [ $i -lt 10 ]
do
    j=$((i + 1))
    l=1
    while [ $l -lt 9 ]
    do
        ../premap $year $i ${TU[$l]} WorldMapKp${i}-Ut${ut[$l]}.out
        l=$((l + 1))
    done
    i=$((i + 1))
done

cd ..
done
echo "Done"
exit 0